### ISSUE TITLE
Can't properly install Xcode 15 beta 

### ISSUE THREAD

**Issue by acercandrito** [outcoldman/outcoldman.com#1]
Hi! First of all, thanks for the awesome explanation to install Diablo IV on Mac Silicon. 
Sadly, I got stuck on the first steps because when I install Xcode 15 beta, I still can't find it anywhere and even the free space on my HD is the same before and after. Could you perhaps know what is going on? I'm running Ventura 13.4 on a M1 Pro 16GB.

**Comment by Bitcoinite** [comment]
Same issue for me.

Do we also need to install Xcode 15 Beta or only Command Line Tools for Xcode 15 Beta?
I don't have any Xcode version installed. After installing Command Line Tools for Xcode 15 Beta, running xcode-select -p returns /Library/Developer/CommandLineTools

There isn't any Xcode.app or Xcode-beta.app in my /Applications/ folder.

If the installation of Xcode is necessary in the first place, then the second question would be what version? On the Apple dev page it says Xcode 15 Beta is only for macOS 14 beta

**Comment by likidu** [comment]
For this particular error `arch: posix_spawnp: zsh: Bad CPU type in executable`, you may run `which zsh` to check if the zsh you are using is coming from Homebrew in lieu of the default one from Apple. As brew only installed the target architecture version which by default is ARM64. A simple way to solve this is to `brew uninstall zsh`. And it will use the Apple's zsh then.
