### ISSUE TITLE
404 - File Not Found

### ISSUE THREAD

**Issue by devfom** [outcoldman/outcoldman.com#2]
Hi,
It looks like this file was lost during migration: http://outcoldman.com/Library/2011/03/17/image_0168E3A9.png

and it's being directly linked in this article http://polycode.livejournal.com/29426.html

**Comment by outcoldman** [comment]
Hey, it should be lowercase `library` http://outcoldman.com/library/2011/03/17/image_0168E3A9.png, I do not own http://polycode.livejournal.com/29426.html.
