### ISSUE TITLE
Consider adding callout that using Game Porting Toolkit 1.0.2 will not work

### ISSUE THREAD

**Issue by villasv** [outcoldman/outcoldman.com#6]
Using 1.0.2 instead of the first 1.0.0 release will leave Diablo IV stuck on a Update loop.

https://www.reddit.com/r/macgaming/comments/14307be/comment/jqdemb0/?utm_source=share&utm_medium=web2x&context=3

**Comment by outcoldman** [comment]
If you do a proper update, it works perfectly https://www.outcoldman.com/en/archive/2023/06/07/playing-diablo-4-on-macos/#how-to-upgrade-to-game-porting-toolkit-102 

Sorry for the late add, but I just tried, and it works without any issues.

**Comment by villasv** [comment]
> If you do a proper update, it works perfectly

Good to know, thanks. I might try updating soon then. But many people would assume that they can just install 1.0.2 from the get go, which doesn't seem to always work. It did not for me. That's the catch that would be nice to know from the start.
