### ISSUE TITLE
No GPUs found! A GPU is required to play Diablo IV.

### ISSUE THREAD

**Issue by sunyu1984** [outcoldman/outcoldman.com#7]
I installed the game porting toolkit, installed Battle.net.exe, and finished downloading Diablo IV. Clicking the Play button returns "No GPUs found! A GPU is required to play Diablo IV. This might occur if you are currently installing GPU drivers."

Could anyone tell me how to fix this issue? How can I install the driver and run the game? I am not good at typing command lines so I really appreciate it if you guys can show me some codes to fix it.

**Comment by outcoldman** [comment]
Are you on M1/M2 or running something else? What version of macOS?
